### ISSUE TITLE
Module error when run

### ISSUE THREAD

**Issue by gustavolucksik** [lamnguyenkhoa/container-code-recognition#3]
Hello lamnguyenkhoa,

Im getting error when run:

`python single_frame_process.py -i images\container1.png -c yolov4.cfg -w yolov4.weights -cl yolov4.txt`

Error:
`code_region_detector/build_model(): loading YOLO from disk...
Traceback (most recent call last):
  File "C:\Users\brgus\Downloads\container-code-recognition-main\single_frame_process.py", line 86, in <module>
    main(argument)
  File "C:\Users\brgus\Downloads\container-code-recognition-main\single_frame_process.py", line 73, in main
    net, classes, output_layers = build_model(args['classes'], args['weights'], args['config'])
  File "C:\Users\brgus\Downloads\container-code-recognition-main\src\code_region_detector.py", line 32, in build_model
    output_layers = [layer_names[i[0] - 1] for i in net.getUnconnectedOutLayers()]  # Get the yolo layer
  File "C:\Users\brgus\Downloads\container-code-recognition-main\src\code_region_detector.py", line 32, in <listcomp>
    output_layers = [layer_names[i[0] - 1] for i in net.getUnconnectedOutLayers()]  # Get the yolo layer
IndexError: invalid index to scalar variable.`

**Comment by lamnguyenkhoa** [comment]
Have you checked issue #2 and tried the solution there? It looks similar to that.

**Comment by gustavolucksik** [comment]
Thank you! now its working.
